// Code generated by MockGen. DO NOT EDIT.
// Source: fpl/server/types.go

// Package mock_server is a generated GoMock package.
package mock_server

import (
	grpc "github.com/go-fantasy/fpl/grpc"
	gomock "github.com/golang/mock/gomock"
	context "golang.org/x/net/context"
	reflect "reflect"
)

// MockFPLServer is a mock of FPLServer interface
type MockFPLServer struct {
	ctrl     *gomock.Controller
	recorder *MockFPLServerMockRecorder
}

// MockFPLServerMockRecorder is the mock recorder for MockFPLServer
type MockFPLServerMockRecorder struct {
	mock *MockFPLServer
}

// NewMockFPLServer creates a new mock instance
func NewMockFPLServer(ctrl *gomock.Controller) *MockFPLServer {
	mock := &MockFPLServer{ctrl: ctrl}
	mock.recorder = &MockFPLServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFPLServer) EXPECT() *MockFPLServerMockRecorder {
	return m.recorder
}

// GetNumberOfPlayers mocks base method
func (m *MockFPLServer) GetNumberOfPlayers(arg0 context.Context, arg1 *grpc.NumPlayerRequest) (*grpc.NumPlayers, error) {
	ret := m.ctrl.Call(m, "GetNumberOfPlayers", arg0, arg1)
	ret0, _ := ret[0].(*grpc.NumPlayers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNumberOfPlayers indicates an expected call of GetNumberOfPlayers
func (mr *MockFPLServerMockRecorder) GetNumberOfPlayers(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNumberOfPlayers", reflect.TypeOf((*MockFPLServer)(nil).GetNumberOfPlayers), arg0, arg1)
}

// GetParticipantsInLeague mocks base method
func (m *MockFPLServer) GetParticipantsInLeague(arg0 context.Context, arg1 *grpc.LeagueCode) (*grpc.NumParticipants, error) {
	ret := m.ctrl.Call(m, "GetParticipantsInLeague", arg0, arg1)
	ret0, _ := ret[0].(*grpc.NumParticipants)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParticipantsInLeague indicates an expected call of GetParticipantsInLeague
func (mr *MockFPLServerMockRecorder) GetParticipantsInLeague(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParticipantsInLeague", reflect.TypeOf((*MockFPLServer)(nil).GetParticipantsInLeague), arg0, arg1)
}

// GetDataForGameweek mocks base method
func (m *MockFPLServer) GetDataForGameweek(arg0 context.Context, arg1 *grpc.GameweekReq) (*grpc.PlayerOccuranceData, error) {
	ret := m.ctrl.Call(m, "GetDataForGameweek", arg0, arg1)
	ret0, _ := ret[0].(*grpc.PlayerOccuranceData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataForGameweek indicates an expected call of GetDataForGameweek
func (mr *MockFPLServerMockRecorder) GetDataForGameweek(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataForGameweek", reflect.TypeOf((*MockFPLServer)(nil).GetDataForGameweek), arg0, arg1)
}

// GetDataForAllGameweeks mocks base method
func (m *MockFPLServer) GetDataForAllGameweeks(arg0 *grpc.LeagueCode, arg1 grpc.FPL_GetDataForAllGameweeksServer) error {
	ret := m.ctrl.Call(m, "GetDataForAllGameweeks", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetDataForAllGameweeks indicates an expected call of GetDataForAllGameweeks
func (mr *MockFPLServerMockRecorder) GetDataForAllGameweeks(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataForAllGameweeks", reflect.TypeOf((*MockFPLServer)(nil).GetDataForAllGameweeks), arg0, arg1)
}

// Start mocks base method
func (m *MockFPLServer) Start(arg0 string) error {
	ret := m.ctrl.Call(m, "Start", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start
func (mr *MockFPLServerMockRecorder) Start(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockFPLServer)(nil).Start), arg0)
}

// MockScraper is a mock of Scraper interface
type MockScraper struct {
	ctrl     *gomock.Controller
	recorder *MockScraperMockRecorder
}

// MockScraperMockRecorder is the mock recorder for MockScraper
type MockScraperMockRecorder struct {
	mock *MockScraper
}

// NewMockScraper creates a new mock instance
func NewMockScraper(ctrl *gomock.Controller) *MockScraper {
	mock := &MockScraper{ctrl: ctrl}
	mock.recorder = &MockScraperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockScraper) EXPECT() *MockScraperMockRecorder {
	return m.recorder
}

// GetTeamInfoForParticipant mocks base method
func (m *MockScraper) GetTeamInfoForParticipant(arg0 map[int64]string, arg1 int, arg2 *[]int64) (map[string]int, error) {
	ret := m.ctrl.Call(m, "GetTeamInfoForParticipant", arg0, arg1, arg2)
	ret0, _ := ret[0].(map[string]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamInfoForParticipant indicates an expected call of GetTeamInfoForParticipant
func (mr *MockScraperMockRecorder) GetTeamInfoForParticipant(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamInfoForParticipant", reflect.TypeOf((*MockScraper)(nil).GetTeamInfoForParticipant), arg0, arg1, arg2)
}

// GetPlayerMapping mocks base method
func (m *MockScraper) GetPlayerMapping() (map[int64]string, error) {
	ret := m.ctrl.Call(m, "GetPlayerMapping")
	ret0, _ := ret[0].(map[int64]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlayerMapping indicates an expected call of GetPlayerMapping
func (mr *MockScraperMockRecorder) GetPlayerMapping() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlayerMapping", reflect.TypeOf((*MockScraper)(nil).GetPlayerMapping))
}

// GetParticipantsInLeague mocks base method
func (m *MockScraper) GetParticipantsInLeague(arg0 int) (*[]int64, error) {
	ret := m.ctrl.Call(m, "GetParticipantsInLeague", arg0)
	ret0, _ := ret[0].(*[]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParticipantsInLeague indicates an expected call of GetParticipantsInLeague
func (mr *MockScraperMockRecorder) GetParticipantsInLeague(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParticipantsInLeague", reflect.TypeOf((*MockScraper)(nil).GetParticipantsInLeague), arg0)
}

// WriteToFile mocks base method
func (m *MockScraper) WriteToFile(arg0 map[int]map[string]int, arg1 int) (string, error) {
	ret := m.ctrl.Call(m, "WriteToFile", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WriteToFile indicates an expected call of WriteToFile
func (mr *MockScraperMockRecorder) WriteToFile(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteToFile", reflect.TypeOf((*MockScraper)(nil).WriteToFile), arg0, arg1)
}

// MockClient is a mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// MakeRequest mocks base method
func (m *MockClient) MakeRequest(arg0 string) ([]byte, error) {
	ret := m.ctrl.Call(m, "MakeRequest", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeRequest indicates an expected call of MakeRequest
func (mr *MockClientMockRecorder) MakeRequest(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeRequest", reflect.TypeOf((*MockClient)(nil).MakeRequest), arg0)
}
