// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/fpl.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00519c44ffdc0ef5, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00519c44ffdc0ef5, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type NumPlayerRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NumPlayerRequest) Reset()         { *m = NumPlayerRequest{} }
func (m *NumPlayerRequest) String() string { return proto.CompactTextString(m) }
func (*NumPlayerRequest) ProtoMessage()    {}
func (*NumPlayerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00519c44ffdc0ef5, []int{2}
}

func (m *NumPlayerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumPlayerRequest.Unmarshal(m, b)
}
func (m *NumPlayerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumPlayerRequest.Marshal(b, m, deterministic)
}
func (m *NumPlayerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumPlayerRequest.Merge(m, src)
}
func (m *NumPlayerRequest) XXX_Size() int {
	return xxx_messageInfo_NumPlayerRequest.Size(m)
}
func (m *NumPlayerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NumPlayerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NumPlayerRequest proto.InternalMessageInfo

type NumPlayers struct {
	NumPlayers           int64    `protobuf:"varint,1,opt,name=numPlayers,proto3" json:"numPlayers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NumPlayers) Reset()         { *m = NumPlayers{} }
func (m *NumPlayers) String() string { return proto.CompactTextString(m) }
func (*NumPlayers) ProtoMessage()    {}
func (*NumPlayers) Descriptor() ([]byte, []int) {
	return fileDescriptor_00519c44ffdc0ef5, []int{3}
}

func (m *NumPlayers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumPlayers.Unmarshal(m, b)
}
func (m *NumPlayers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumPlayers.Marshal(b, m, deterministic)
}
func (m *NumPlayers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumPlayers.Merge(m, src)
}
func (m *NumPlayers) XXX_Size() int {
	return xxx_messageInfo_NumPlayers.Size(m)
}
func (m *NumPlayers) XXX_DiscardUnknown() {
	xxx_messageInfo_NumPlayers.DiscardUnknown(m)
}

var xxx_messageInfo_NumPlayers proto.InternalMessageInfo

func (m *NumPlayers) GetNumPlayers() int64 {
	if m != nil {
		return m.NumPlayers
	}
	return 0
}

type LeagueCode struct {
	LeagueCode           int64    `protobuf:"varint,1,opt,name=LeagueCode,proto3" json:"LeagueCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeagueCode) Reset()         { *m = LeagueCode{} }
func (m *LeagueCode) String() string { return proto.CompactTextString(m) }
func (*LeagueCode) ProtoMessage()    {}
func (*LeagueCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_00519c44ffdc0ef5, []int{4}
}

func (m *LeagueCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeagueCode.Unmarshal(m, b)
}
func (m *LeagueCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeagueCode.Marshal(b, m, deterministic)
}
func (m *LeagueCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeagueCode.Merge(m, src)
}
func (m *LeagueCode) XXX_Size() int {
	return xxx_messageInfo_LeagueCode.Size(m)
}
func (m *LeagueCode) XXX_DiscardUnknown() {
	xxx_messageInfo_LeagueCode.DiscardUnknown(m)
}

var xxx_messageInfo_LeagueCode proto.InternalMessageInfo

func (m *LeagueCode) GetLeagueCode() int64 {
	if m != nil {
		return m.LeagueCode
	}
	return 0
}

type NumParticipants struct {
	NumParticipants      int64    `protobuf:"varint,1,opt,name=numParticipants,proto3" json:"numParticipants,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NumParticipants) Reset()         { *m = NumParticipants{} }
func (m *NumParticipants) String() string { return proto.CompactTextString(m) }
func (*NumParticipants) ProtoMessage()    {}
func (*NumParticipants) Descriptor() ([]byte, []int) {
	return fileDescriptor_00519c44ffdc0ef5, []int{5}
}

func (m *NumParticipants) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumParticipants.Unmarshal(m, b)
}
func (m *NumParticipants) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumParticipants.Marshal(b, m, deterministic)
}
func (m *NumParticipants) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumParticipants.Merge(m, src)
}
func (m *NumParticipants) XXX_Size() int {
	return xxx_messageInfo_NumParticipants.Size(m)
}
func (m *NumParticipants) XXX_DiscardUnknown() {
	xxx_messageInfo_NumParticipants.DiscardUnknown(m)
}

var xxx_messageInfo_NumParticipants proto.InternalMessageInfo

func (m *NumParticipants) GetNumParticipants() int64 {
	if m != nil {
		return m.NumParticipants
	}
	return 0
}

type GameweekReq struct {
	LeagueCode           int64    `protobuf:"varint,1,opt,name=LeagueCode,proto3" json:"LeagueCode,omitempty"`
	Gameweek             int64    `protobuf:"varint,2,opt,name=Gameweek,proto3" json:"Gameweek,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameweekReq) Reset()         { *m = GameweekReq{} }
func (m *GameweekReq) String() string { return proto.CompactTextString(m) }
func (*GameweekReq) ProtoMessage()    {}
func (*GameweekReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00519c44ffdc0ef5, []int{6}
}

func (m *GameweekReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameweekReq.Unmarshal(m, b)
}
func (m *GameweekReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameweekReq.Marshal(b, m, deterministic)
}
func (m *GameweekReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameweekReq.Merge(m, src)
}
func (m *GameweekReq) XXX_Size() int {
	return xxx_messageInfo_GameweekReq.Size(m)
}
func (m *GameweekReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GameweekReq.DiscardUnknown(m)
}

var xxx_messageInfo_GameweekReq proto.InternalMessageInfo

func (m *GameweekReq) GetLeagueCode() int64 {
	if m != nil {
		return m.LeagueCode
	}
	return 0
}

func (m *GameweekReq) GetGameweek() int64 {
	if m != nil {
		return m.Gameweek
	}
	return 0
}

type PlayerOccuranceData struct {
	PlayerOccurance      map[string]int32 `protobuf:"bytes,1,rep,name=playerOccurance,proto3" json:"playerOccurance,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PlayerOccuranceData) Reset()         { *m = PlayerOccuranceData{} }
func (m *PlayerOccuranceData) String() string { return proto.CompactTextString(m) }
func (*PlayerOccuranceData) ProtoMessage()    {}
func (*PlayerOccuranceData) Descriptor() ([]byte, []int) {
	return fileDescriptor_00519c44ffdc0ef5, []int{7}
}

func (m *PlayerOccuranceData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerOccuranceData.Unmarshal(m, b)
}
func (m *PlayerOccuranceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerOccuranceData.Marshal(b, m, deterministic)
}
func (m *PlayerOccuranceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerOccuranceData.Merge(m, src)
}
func (m *PlayerOccuranceData) XXX_Size() int {
	return xxx_messageInfo_PlayerOccuranceData.Size(m)
}
func (m *PlayerOccuranceData) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerOccuranceData.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerOccuranceData proto.InternalMessageInfo

func (m *PlayerOccuranceData) GetPlayerOccurance() map[string]int32 {
	if m != nil {
		return m.PlayerOccurance
	}
	return nil
}

type AllGameweekData struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllGameweekData) Reset()         { *m = AllGameweekData{} }
func (m *AllGameweekData) String() string { return proto.CompactTextString(m) }
func (*AllGameweekData) ProtoMessage()    {}
func (*AllGameweekData) Descriptor() ([]byte, []int) {
	return fileDescriptor_00519c44ffdc0ef5, []int{8}
}

func (m *AllGameweekData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllGameweekData.Unmarshal(m, b)
}
func (m *AllGameweekData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllGameweekData.Marshal(b, m, deterministic)
}
func (m *AllGameweekData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllGameweekData.Merge(m, src)
}
func (m *AllGameweekData) XXX_Size() int {
	return xxx_messageInfo_AllGameweekData.Size(m)
}
func (m *AllGameweekData) XXX_DiscardUnknown() {
	xxx_messageInfo_AllGameweekData.DiscardUnknown(m)
}

var xxx_messageInfo_AllGameweekData proto.InternalMessageInfo

func (m *AllGameweekData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "grpc.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "grpc.HelloReply")
	proto.RegisterType((*NumPlayerRequest)(nil), "grpc.NumPlayerRequest")
	proto.RegisterType((*NumPlayers)(nil), "grpc.NumPlayers")
	proto.RegisterType((*LeagueCode)(nil), "grpc.LeagueCode")
	proto.RegisterType((*NumParticipants)(nil), "grpc.numParticipants")
	proto.RegisterType((*GameweekReq)(nil), "grpc.GameweekReq")
	proto.RegisterType((*PlayerOccuranceData)(nil), "grpc.PlayerOccuranceData")
	proto.RegisterMapType((map[string]int32)(nil), "grpc.PlayerOccuranceData.PlayerOccuranceEntry")
	proto.RegisterType((*AllGameweekData)(nil), "grpc.AllGameweekData")
}

func init() { proto.RegisterFile("grpc/fpl.proto", fileDescriptor_00519c44ffdc0ef5) }

var fileDescriptor_00519c44ffdc0ef5 = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xcb, 0x8e, 0xd3, 0x40,
	0x10, 0x8c, 0xe3, 0x2c, 0x8f, 0xde, 0x15, 0x09, 0xcd, 0xb2, 0x18, 0x1f, 0xd0, 0x6a, 0x24, 0x50,
	0x0e, 0xc8, 0xa0, 0xe5, 0x82, 0xe0, 0xc2, 0x63, 0x77, 0x21, 0x52, 0x94, 0x44, 0x3e, 0x71, 0x9d,
	0x38, 0x1d, 0x2b, 0xca, 0xf8, 0x91, 0xf1, 0x18, 0xe4, 0x5f, 0xe1, 0x37, 0xf8, 0x41, 0x34, 0x63,
	0x3b, 0x36, 0x26, 0xd1, 0xde, 0xa6, 0x2a, 0xd5, 0x9d, 0xea, 0x2a, 0x19, 0x1e, 0x85, 0x32, 0x0d,
	0xde, 0xac, 0x53, 0xe1, 0xa5, 0x32, 0x51, 0x09, 0x0e, 0x34, 0x66, 0x0c, 0xce, 0xbe, 0x93, 0x10,
	0x89, 0x4f, 0xbb, 0x9c, 0x32, 0x85, 0x08, 0x83, 0x98, 0x47, 0xe4, 0x58, 0x97, 0xd6, 0xf8, 0xa1,
	0x6f, 0xde, 0xec, 0x15, 0x40, 0xa5, 0x49, 0x45, 0x81, 0x0e, 0xdc, 0x8f, 0x28, 0xcb, 0x78, 0x58,
	0x8b, 0x6a, 0xc8, 0x10, 0x46, 0xb3, 0x3c, 0x5a, 0x08, 0x5e, 0x90, 0xac, 0xf6, 0xb1, 0xd7, 0x00,
	0x7b, 0x2e, 0xc3, 0x17, 0x00, 0xf1, 0x1e, 0x99, 0x71, 0xdb, 0x6f, 0x31, 0x5a, 0x3d, 0x25, 0x1e,
	0xe6, 0xf4, 0x35, 0x59, 0x91, 0x56, 0x37, 0xa8, 0x56, 0x37, 0x0c, 0xfb, 0x08, 0x43, 0x3d, 0xcb,
	0xa5, 0xda, 0x04, 0x9b, 0x94, 0xc7, 0x2a, 0xc3, 0xf1, 0x7f, 0x54, 0x35, 0xd7, 0xa5, 0xd9, 0x04,
	0x4e, 0xbf, 0xf1, 0x88, 0x7e, 0x11, 0x6d, 0x7d, 0xda, 0xdd, 0xf5, 0x5f, 0xe8, 0xc2, 0x83, 0x5a,
	0xee, 0xf4, 0xcd, 0xaf, 0x7b, 0xcc, 0xfe, 0x58, 0xf0, 0xa4, 0xbc, 0x60, 0x1e, 0x04, 0xb9, 0xe4,
	0x71, 0x40, 0xd7, 0x5c, 0x71, 0xfc, 0x01, 0xc3, 0xf4, 0x5f, 0xda, 0xb1, 0x2e, 0xed, 0xf1, 0xe9,
	0x95, 0xe7, 0xe9, 0xec, 0xbd, 0x03, 0x33, 0x5d, 0xee, 0x26, 0x56, 0xb2, 0xf0, 0xbb, 0x6b, 0xdc,
	0x2f, 0x70, 0x7e, 0x48, 0x88, 0x23, 0xb0, 0xb7, 0x54, 0x54, 0xbd, 0xe8, 0x27, 0x9e, 0xc3, 0xc9,
	0x4f, 0x2e, 0x72, 0x32, 0xa6, 0x4f, 0xfc, 0x12, 0x7c, 0xe8, 0xbf, 0xb7, 0xd8, 0x4b, 0x18, 0x7e,
	0x16, 0xa2, 0x3e, 0xc2, 0x18, 0x46, 0x18, 0xac, 0xb8, 0xe2, 0x66, 0xfe, 0xcc, 0x37, 0xef, 0xab,
	0xdf, 0x7d, 0xb0, 0x6f, 0x17, 0x53, 0xfc, 0x04, 0x18, 0x92, 0x9a, 0xe5, 0xd1, 0x92, 0xe4, 0x7c,
	0x5d, 0x17, 0x7a, 0x51, 0x5e, 0xd2, 0xad, 0xdd, 0x1d, 0x75, 0xf8, 0x8c, 0xf5, 0xf0, 0x1a, 0x9e,
	0x85, 0xa4, 0xda, 0x25, 0x4c, 0xe2, 0x32, 0x61, 0xac, 0xe4, 0x4d, 0xde, 0xee, 0xd3, 0x92, 0xe9,
	0xb6, 0xa6, 0xb7, 0x68, 0x1f, 0xda, 0xee, 0x6d, 0x22, 0x6b, 0xf7, 0xf8, 0xb8, 0x94, 0xb7, 0x1a,
	0x75, 0x9f, 0x1f, 0x0d, 0x99, 0xf5, 0xf0, 0x06, 0x2e, 0x9a, 0x2d, 0xad, 0x18, 0xb2, 0xe3, 0x56,
	0x3a, 0x61, 0xb1, 0xde, 0x5b, 0x6b, 0x79, 0xcf, 0x7c, 0x4a, 0xef, 0xfe, 0x06, 0x00, 0x00, 0xff,
	0xff, 0x35, 0xc0, 0xdd, 0x4c, 0x5c, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FPLClient is the client API for FPL service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FPLClient interface {
	GetNumberOfPlayers(ctx context.Context, in *NumPlayerRequest, opts ...grpc.CallOption) (*NumPlayers, error)
	GetParticipantsInLeague(ctx context.Context, in *LeagueCode, opts ...grpc.CallOption) (*NumParticipants, error)
	GetDataForGameweek(ctx context.Context, in *GameweekReq, opts ...grpc.CallOption) (*PlayerOccuranceData, error)
	GetDataForAllGameweeks(ctx context.Context, in *LeagueCode, opts ...grpc.CallOption) (FPL_GetDataForAllGameweeksClient, error)
}

type fPLClient struct {
	cc *grpc.ClientConn
}

func NewFPLClient(cc *grpc.ClientConn) FPLClient {
	return &fPLClient{cc}
}

func (c *fPLClient) GetNumberOfPlayers(ctx context.Context, in *NumPlayerRequest, opts ...grpc.CallOption) (*NumPlayers, error) {
	out := new(NumPlayers)
	err := c.cc.Invoke(ctx, "/grpc.FPL/getNumberOfPlayers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fPLClient) GetParticipantsInLeague(ctx context.Context, in *LeagueCode, opts ...grpc.CallOption) (*NumParticipants, error) {
	out := new(NumParticipants)
	err := c.cc.Invoke(ctx, "/grpc.FPL/getParticipantsInLeague", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fPLClient) GetDataForGameweek(ctx context.Context, in *GameweekReq, opts ...grpc.CallOption) (*PlayerOccuranceData, error) {
	out := new(PlayerOccuranceData)
	err := c.cc.Invoke(ctx, "/grpc.FPL/getDataForGameweek", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fPLClient) GetDataForAllGameweeks(ctx context.Context, in *LeagueCode, opts ...grpc.CallOption) (FPL_GetDataForAllGameweeksClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FPL_serviceDesc.Streams[0], "/grpc.FPL/getDataForAllGameweeks", opts...)
	if err != nil {
		return nil, err
	}
	x := &fPLGetDataForAllGameweeksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FPL_GetDataForAllGameweeksClient interface {
	Recv() (*AllGameweekData, error)
	grpc.ClientStream
}

type fPLGetDataForAllGameweeksClient struct {
	grpc.ClientStream
}

func (x *fPLGetDataForAllGameweeksClient) Recv() (*AllGameweekData, error) {
	m := new(AllGameweekData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FPLServer is the server API for FPL service.
type FPLServer interface {
	GetNumberOfPlayers(context.Context, *NumPlayerRequest) (*NumPlayers, error)
	GetParticipantsInLeague(context.Context, *LeagueCode) (*NumParticipants, error)
	GetDataForGameweek(context.Context, *GameweekReq) (*PlayerOccuranceData, error)
	GetDataForAllGameweeks(*LeagueCode, FPL_GetDataForAllGameweeksServer) error
}

func RegisterFPLServer(s *grpc.Server, srv FPLServer) {
	s.RegisterService(&_FPL_serviceDesc, srv)
}

func _FPL_GetNumberOfPlayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NumPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FPLServer).GetNumberOfPlayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.FPL/GetNumberOfPlayers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FPLServer).GetNumberOfPlayers(ctx, req.(*NumPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FPL_GetParticipantsInLeague_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeagueCode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FPLServer).GetParticipantsInLeague(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.FPL/GetParticipantsInLeague",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FPLServer).GetParticipantsInLeague(ctx, req.(*LeagueCode))
	}
	return interceptor(ctx, in, info, handler)
}

func _FPL_GetDataForGameweek_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameweekReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FPLServer).GetDataForGameweek(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.FPL/GetDataForGameweek",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FPLServer).GetDataForGameweek(ctx, req.(*GameweekReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FPL_GetDataForAllGameweeks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LeagueCode)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FPLServer).GetDataForAllGameweeks(m, &fPLGetDataForAllGameweeksServer{stream})
}

type FPL_GetDataForAllGameweeksServer interface {
	Send(*AllGameweekData) error
	grpc.ServerStream
}

type fPLGetDataForAllGameweeksServer struct {
	grpc.ServerStream
}

func (x *fPLGetDataForAllGameweeksServer) Send(m *AllGameweekData) error {
	return x.ServerStream.SendMsg(m)
}

var _FPL_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.FPL",
	HandlerType: (*FPLServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getNumberOfPlayers",
			Handler:    _FPL_GetNumberOfPlayers_Handler,
		},
		{
			MethodName: "getParticipantsInLeague",
			Handler:    _FPL_GetParticipantsInLeague_Handler,
		},
		{
			MethodName: "getDataForGameweek",
			Handler:    _FPL_GetDataForGameweek_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "getDataForAllGameweeks",
			Handler:       _FPL_GetDataForAllGameweeks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpc/fpl.proto",
}
